config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :updates
  end
  devise_for :users
  resources :users, :only => [:show]
  
  match 'users/:id' => 'users#show', via: :get
  
  get 'pages/home'
  root "projects#index"
  get "about" => "pages#about"
  get "myprojects" => "projects#myprojects"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :updates, dependent: :destroy
  has_attached_file :finished_image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :finished_image, :content_type => /\Aimage\/.*\Z/
  
  validates :finished_image, presence: true
  validates :name, presence: true
  validates :name, uniqueness: true
  
end

app/models/update.rb
class Update < ActiveRecord::Base
  belongs_to :project
  has_attached_file :update_image, 
    styles: {
    medium: '300x300>'
  }
  

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :update_image, :content_type => /\Aimage\/.*\Z/
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, dependent: :destroy
  validates :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :username
     devise_parameter_sanitizer.for(:account_update) << :username
 end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about 
  end 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def myprojects
    @projects = current_user.projects.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end
  
  
  def index
    @projects = Project.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  def show
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
    end

    def correct_user
      @project = current_user.projects.find_by(id: params[:id])
      redirect_to projects_path, notice: "Not authorized to edit this project" if @project.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:description, :name, :finished_image)
    end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @update = @project.updates.create(update_params)
    redirect_to project_path(@project)
  end

  def destroy
    if params[:project_id]
      @project = Project.find(params[:project_id])
      @update = @project.updates.find(params[:id])
      @update.destroy
    end
    
    def show
      #1st you retrieve the post thanks to params[:post_id]
      project = Project.find(params[:project_id])
    #2nd you retrieve the comment thanks to params[:id]
      @update = project.updates.find(params[:id])
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
 
  private
  
  def find_project
    @project = Project.find(params[:project_id])
  end
  def update_params
    params.require(:update).permit(:hours, :update_date, :update_image, :update_image_file_name)
    end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_username(params[:id])
    if @user
      @projects = @user.projects.all
      render action: :show
    else
      render file: 'public/404', project:404, formats:[:html]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-6393432-17', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">My Stitching</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <!--<li><%= link_to "About", about_path %></li>-->
        <% if user_signed_in? %>
      <li>
        <%= link_to new_project_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Project
            <% end %>
          </li>
          <li><%= link_to "My Projects", myprojects_path %></li>
          <li><%= link_to current_user.username, edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mystitching</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript">
  var trak=trak||[];trak.io=trak.io||{};trak.io.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"===document.location.protocol?"https://":"http://")+"d29p64779x43zo.cloudfront.net/v1/trak.io.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);var r=function(e){return function(){trak.push([e].concat(Array.prototype.slice.call(arguments,0)))}},i=["initialize","identify","track","alias","channel","source","host","protocol","page_view"];for(var s=0;s<i.length;s++) trak.io[i[s]]=r(i[s]);trak.io.initialize.apply(trak.io,arguments)};
  trak.io.load('14dbe818f62fafcf4f49c83813e26b1ce2ac8fa7', { automagic: true });
</script>
</head>
<body>
<%= render 'layouts/header' %>
  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
<div class="container">
<%= yield %>
</div>
  <footer>
      <%= render 'layouts/footer' %>
    </footer>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Welcome to My Stitching!</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb
<h1>About US</h1>
<p>We are working on our One Month Rails Pinteresting app</p>

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, size: "24x6", class: "form-control" %>
  </div>
<div class="form-group">
  <%= f.label :finsihed_image %>
  <%= f.file_field :finished_image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div id="projects" class="transitions-enabled">
  <% @projects.each do |project| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(project.finished_image.url(:medium)), project %>
      <div class="panel-body">
        <h4><%= project.name %></h4>
        <%= project.user.username if project.user %>
        <% if current_user && project.user == current_user %>
        <%= link_to edit_project_path(project) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
        <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/projects/myprojects.html.erb
<div id="projects" class="transitions-enabled">
  <% @projects.each do |project| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(project.finished_image.url(:medium)), project %>
      <div class="panel-body">
        <h4><%= project.name %></h4>
        <p><strong><%= project.user.username if project.user %></strong></p>
        <% if current_user && project.user == current_user %>
        <%= link_to edit_project_path(project) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
        <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path, class: "btn btn-primary" %>
<div class="row">
  <div class="col-md-offset-2 col-md-8">  
    <div class="panel panel-default">
          <div class="panel-body">
             <div class="col-md-6">
        <%= image_tag @project.finished_image.url(:medium), class: "img-thumbnail"  %>
  </div>

  <div class="col-md-4">
    <p><strong><h4><%= @project.name %></h4></strong><p>
    <p><strong>by <%= @project.user.username if @project.user %></strong></p>
    <p><%= @project.description %></p>
    <% if @project.user == current_user %>
<%= link_to edit_project_path(@project) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
        <%= link_to @project, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
    <% else %>
    
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% if @project.user == current_user %>
<div class="row">
  <div class="col-md-offset-2 col-md-8"> 
    <!--<div class="panel-group" id="accordion">-->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          <button type="button" class="btn btn-primary">Add a New Update</button> 
          </a>
          </h4>
       </div>
       <div id="collapseTwo" class="panel-collapse collapse">
         <div class="panel-body">
          <%= form_for([@project, @project.updates.build], :html => { :multipart => true  }) do |f| %>
           <div class="form-group">
             <%= f.label :update_image %>
             <%= f.file_field :update_image, class: "form-control" %>
          </div>  
          <div class="form-group">
            <%= f.label :hours %>
            <%= f.text_field :hours, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group">
          <%= f.label :update_date %><br />
          <%= f.date_field :update_date, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-primary" %>
        </div>
    <% end %>
       <!--</div>-->
     </div>
    </div>
   </div>
  </div>
</div>
<% end %>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
            <button type="button" class="btn btn-primary">My Updates</button>
          </a>
        </h4>
       </div>
       <div id="collapseOne" class="panel-collapse collapse.in">
         <div class="panel-body">
           <div id="updates" class="transitions-enabled"> 
            <% @project.updates.order("update_date desc").each_with_index do |update, index| %>
            <div class="box">
              <%= image_tag update.update_image.url(:medium), class: "img-thumbnail" %>
              <h4 class="center"><%= update.hours %> hours on <%= update.update_date.strftime("%d/%m/%y") %></h4>
              <% if @project.user == current_user %>
              <p class="center">
                <%= link_to 'Destroy Update', [update.project, update],
                 method: :delete,
                 data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs" %>
              
              <% end %>
              <!-- Button trigger modal -->
                <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#MyModal<%= index %>">
                  View Update
                </button>

                <!-- Modal -->
              <div class="modal fade" id="MyModal<%= index %>" tabindex="-1" role="dialog" aria-labelledby="<%= update.update_date.strftime("%d/%m/%y") %>" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="<%= update.update_date.strftime("%d/%m/%y") %>"><%= update.update_date.strftime("%d/%m/%y") %></h4>
                      </div>
                      <div class="modal-body">
                        <%= image_tag update.update_image.url, class: "img-thumbnail" %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
              </p>
            </div>
            <% end %>
           </div>
         </div>
       </div>
    </div>
  </div>

app/views/updates/show.html.erb
<div class="box">
  <h4 class="center"><%= @update.update_image %> hours on</h4>
</div>

app/views/users/show.html.erb
<div class="page-header">
<h1><%= @user.username %></h1>
</div>
<% if @projects %>
<h2>My Projects</h2>
<div class="panel panel-default">
  <div class="panel-body">
<div id="projects" class="transitions-enabled">
  <% @projects.each do |project| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(project.finished_image.url(:medium)), project %>
      <div class="panel-body">
        <h4><%= project.name %></h4>
        <% if current_user && project.user == current_user %>
        <%= link_to edit_project_path(project) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
        <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>
<% end %>